### ISSUE TITLE
openjdk-7-jre necessary for Seafile CE?

### ISSUE THREAD

**Issue by Seviks** [SeafileDE/seafile-server-installer#26]
Hi

Thank your very much for your installer. I've tried it out on my test server and noticed that it installs a lot of packages. More a question than an issue:
Does Seafile CE really requires openjdk-7-jre? Or maybe there is another reason why the package (and all its dependecies) is included?

I'm using the following file
 seafile-server-installer/debian/seafile-ce_debian

On line 272 we have:
apt-get install sudo python-setuptools python-simplejson python-imaging python-mysqldb \
openjdk-7-jre memcached python-memcache pwgen curl openssl -y

**Comment by alexanderjackson** [comment]
Thanks for pointing this out!

I removed openjdk-7-jre, since it's not necessary for Seafile CE: https://github.com/SeafileDE/seafile-server-installer/commit/a83a8baba209a384d6b0a6c81f231fd8c2243812
