### ISSUE TITLE
Add "_" to SERVER_NAME, if the retrieved hostname is less than 2 characters long

### ISSUE THREAD

**Issue by alexanderjackson** [SeafileDE/seafile-server-installer#33]
Add "_" to SERVER_NAME, if the retrieved hostname is less than 2 characters long. With something like

```
SERVER_NAME=$(hostname -s | cut -c -16)
while test "${#SERVER_NAME}" -lt 2; do SERVER_NAME="${SERVER_NAME}_"; done
```

https://forum.seafile-server.org/t/seafile-server-installer-debian-ubuntu-centos-suse-uberspace/1464/50?u=alexanderjackson

**Comment by shoeper** [comment]
has been implemented.
