### ISSUE TITLE
generate new ssl certificate in change hostname script

### ISSUE THREAD

**Issue by sideshowbob84** [SeafileDE/seafile-server-installer#39]
Hey,
if the hostname ist changed the new hostname must be the commonName of the ssl certificate too. Otherwise the client will not connect. I generated a new ssl certificate and only changed the commonName in the config file.
Thanks for this nice script and regards
Thomas

**Comment by SyncwerkGmbH** [comment]
Yes, that's correct. The hostname used to connect with Seafile clients needs to match against a commonName given in the certificate. Otherwise the clients will not be able to sync. Manual recreating the certificate and restarting NGINX, solves this issue.
