### ISSUE TITLE
seafile-pro_centos-7-amd64

### ISSUE THREAD

**Issue by gcasella** [SeafileDE/seafile-server-installer#41]
seafile-pro_centos-7-amd64 is still listed as version 4.3.2

is there any issue to modify this file to specify 4.3.3 since that is the version i have grabbed from the seafile website?

**Comment by SyncwerkGmbH** [comment]
Yes, you can manually change the version number. However i just updated the installer to automatically find and install the latest Seafile Professional sources which can be found at "/usr/src/seafile/".
