### ISSUE TITLE
do not modify nginx user

### ISSUE THREAD

**Issue by shoeper** [SeafileDE/seafile-server-installer#45]
https://forum.seafile-server.org/t/probleme-mit-dem-seafile-ce-ubuntu-trusty-arm-installer/2875/15?u=shoeper

**Comment by SyncwerkGmbH** [comment]
This issue is solved in the meantime. On Ubuntu Trust (ARM) we now use the OS default packages for NGINX. Therefor the user has been changed from "nginx" to "www-data".
