### ISSUE TITLE
File Upload Failed

### ISSUE THREAD

**Issue by cwtopel** [SeafileDE/seafile-server-installer#47]
Default install has an issue where it does not allow file uploads via the web GUI. 

Seafile returns "File Upload failed" and "Unknown error" in red. A quick Googleing of the issue looks like it's some sort of permission based issue. Possibly nginx related. 

OS: Debian Jessie 64
Fresh Install

**Comment by alexanderjackson** [comment]
Permissions are set correctly by the installers. Did you perhaps update the server manually after the initial install?
