### ISSUE TITLE
EMAIL_BACKEND is missing

### ISSUE THREAD

**Issue by aknoth** [SeafileDE/seafile-server-installer#51]
Hi,

after several hours of investigation I add

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

to  seahub_settings.py and voila - I could send Emails from within Seafile.

Please add this entry to your script (I use Debian Jessie).

**Comment by alexanderjackson** [comment]
Which installer are you referring to?

**Comment by alexanderjackson** [comment]
So I guess there is no issue after all ;-)
