### ISSUE TITLE
review script for v5 and test it

### ISSUE THREAD

**Issue by shoeper** [SeafileDE/seafile-server-installer#58]

**Comment by alexanderjackson** [comment]
https://github.com/SeafileDE/seafile-server-installer/blob/master/seafile_v5_debian is ready.

**Comment by haoglehaogle** [comment]
Get 502 no getway error, and only found port 11211, 443 ,80 working.

**Comment by jaltek** [comment]
Same here:

```
# systemctl status seafile
● seafile.service - Seafile Server
   Loaded: loaded (/etc/systemd/system/seafile.service; enabled)
   Active: failed (Result: exit-code) since Tue 2016-02-02 13:10:49 CET; 2min 55s ago
  Process: 9509 ExecStart=/opt/seafile/seafile-server-latest/seafile.sh start (code=exited, status=255)
 Main PID: 9509 (code=exited, status=255)

Feb 02 13:10:49 debian seafile.sh[9509]: Error: there is no ccnet config directory.
Feb 02 13:10:49 debian seafile.sh[9509]: Have you run setup-seafile.sh before this?
Feb 02 13:10:49 debian systemd[1]: seafile.service: main process exited, code=exited, status=255/n/a
Feb 02 13:10:49 debian systemd[1]: Failed to start Seafile Server.
Feb 02 13:10:49 debian systemd[1]: Unit seafile.service entered failed state.
```

**Comment by alexanderjackson** [comment]
Please upload your install logs at https://app.seafile.de/u/d/b184c70699/ and I will debug the issue. Thanks!

**Comment by jaltek** [comment]
Done :)

**Comment by alexanderjackson** [comment]
@jaltek You need to setup the server with a fully-qualified hostname before running the installer. The output of `hostname -f` must result in a FQDN. Then the installer should work for you. Please restart with a fresh machine.

**Comment by jaltek** [comment]
I tried a fresh install (testing with a debian jessie minimal inside Virtualbox). This time with a FQDN hostname and unfortunately with the same issue as mentioned above.

Maybe this part is the problem?

```
+ /opt/seafile//seafile-server-4.4.6//seafile/bin/ccnet-init -c /opt/seafile//ccnet --name debian --host debian.xxxxxx.local -F /opt/seafile//conf
/opt/seafile//seafile-server-4.4.6//seafile/bin/ccnet-init: invalid option -- 'F'
Usage: /opt/seafile//seafile-server-4.4.6//seafile/bin/ccnet-init [OPTION]...
Init ccnet configuration directory.

Mandatory arguments to long options are mandatory for short options too.
  -c, --config-dir=DIR      use DIR as the output ccnet configuration
                              directory. Default is ~/.ccnet
  -n, --name=NAME           your public name
  -H, --host=<ip or domain> Public addr. Only useful for server.
  -P, --port=port           Public port. Only useful for server.
                            Default 10001.

```

**Comment by vjrj** [comment]
Same error here. This happens because the script download a version that don't have this `-F` option for x86-64 systems. See the comment:

```
# Disabled on 2015-11-13 due to issues with the Bintray repository. x86-64 is broke, i386 seems to be ok.
```

Downloading `5.0.4` version this `ccnet-init` part works. 

I found other issue starting seafile:
`SQLException: Failed to start connection pool seafile`
because seafile@localhost cannont connect to the database. I solved it doing the three `GRANT` statements with `IDENTIFIED BY` and later `FLUSH PRIVILEGES`.

After that seafile started correctly.
