### ISSUE TITLE
add tags for versions

### ISSUE THREAD

**Issue by shoeper** [SeafileDE/seafile-server-installer#59]
tags should represent the Seafile version the script is compatible with.

**Comment by alexanderjackson** [comment]
As an intermediate solution I renamed the Debian installers accordingly. The other installers are not updated yet and will not yet work with Seafile V5.

**Comment by shoeper** [comment]
@alexanderjackson another idea came to my mind. We could remove non working version before creating tags. If we later want to get them back we could simply checkout an older version, create a branch, fix the script and merge it with master.

**Comment by alexanderjackson** [comment]
I'm closing this issue since we are restructuring the Syncwerk installation method all together.
