### ISSUE TITLE
eth0 is not longer used on CentOS 7

### ISSUE THREAD

**Issue by H8to** [SeafileDE/seafile-server-installer#60]
It's now ens0,eno1 etc.
http://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/

For people having issues you can disable this new method via a symlink:
ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules

**Comment by felagsw** [comment]
CentOS script has been upgraded, and I believe this issue is now resolved (feel free to reopen, if needed).
