### ISSUE TITLE
setup of external apt repositories

### ISSUE THREAD

**Issue by amie42** [SeafileDE/seafile-server-installer#61]
Hi seafilers, 

I highly appreciate your work, however I would also appreciate if you would not abuse the trust a user of your setup script grants to you. Your setup script requires root privileges of course. IMHO such a script must not install external sources of code into a system without letting the user know about that. In your case, the source is "only" nginx which is kind of trustworthy, but the user should have at least the option to decline this or use the default version shipped with the given distribution. If that is not possible with your great product, you could also offer to use the backports repository or reduce the features supported in this installation. 

keep on with the awesome work

cheers 
Amie

**Comment by shoeper** [comment]
This script as it is, is made for setting up a server with the only purpose to serve Seafile.

**Comment by alexanderjackson** [comment]
I do understand your concerns. In one of the earlier versions of the README.md's (e.g. https://github.com/SeafileDE/seafile-server-installer/blob/ede57fadb4252d0fad9b40c77af3492642f6221e/README.md) I did actually mention this fact. However, alternatively the OS NGINX source may be safely used as well. I'll think about an option or revert back to the default OS packages...

**Comment by shoeper** [comment]
That leads to problems using spdy/http2.

**Comment by alexanderjackson** [comment]
Yes, I know. This was one of the main reasons why I initially preferred the nginx.org sources. However, I think the presence of these protocol extensions can safely be neglected.

**Comment by shoeper** [comment]
I've removed the nginx repo.

**Comment by amie42** [comment]
Thanks :+1:
