### ISSUE TITLE
seafile-pro_centos-7-amd64: conf files in incorrect directories

### ISSUE THREAD

**Issue by brennmiddag** [SeafileDE/seafile-server-installer#66]
It seems this issue has been resolved for the community version but not for the pro version.
The pro installer still puts the conf files in the pre 5.0 locations, thus seafile fails to start since it can't find the conf files.

I guess a lot of fixes to the community edition should/could be pushed to the pro installer as well..

regards,

brenn

**Comment by shoeper** [comment]
The issue is that only https://github.com/SeafileDE/seafile-server-installer/blob/master/seafile_v5_debian has been updated so far.
