### ISSUE TITLE
bad ccnet.conf location and Unknown command: 'run_gunicorn'

### ISSUE THREAD

**Issue by vince06fr** [SeafileDE/seafile-server-installer#67]
after a succesfull ubuntu installation, first i had to copy the ccnet.conf on the new location (http://manual.seafile.com/deploy/new_directory_layout_5_0_0.html) for starting seafile

Then I try to start seahub and I get 

```
Unknown command: 'run_gunicorn'
Type 'manage.py help' for usage.
Error:Seahub failed to start.
```

I try to apt-get install gunicorn but there is no change..
So I check /opt/seafile/seafile-server-latest/seahub/seahub, gunicorn was absent from the INSTALLED_APPS settings.

add gunicorn to the INSTALLED_APPS and  seahub can start

**Comment by alexanderjackson** [comment]
The described problem is not related to the offered installers. I'm closing the issue.
