### ISSUE TITLE
Is the python dependency really such a good idea?

### ISSUE THREAD

**Issue by jult** [SeafileDE/seafile-server-installer#68]
Posting this question because on the average NAS people buy out there, the python modules required for seafile server open a huge can of worms.
Why not do what syncthing does? Or add that as an option, so we can bypass the python and database install dependencies for these devices.

Currently, as it stands:
- syncthing install on random NAS took me 10 minutes
- seafile install on random NAS is taking me days, because of missing dependencies (and I still don't have it running..)

**Comment by shoeper** [comment]
I don't understand the question. Seahub requires python. Without python Seafile does not work.

**Comment by jult** [comment]
What's so hard to understand? Maybe do a complete rewrite and stop requiring obscure python modules? As soon as syncthing adopts a multi-user interface, and client-side encryption, the entire seafile project will probably die.

**Comment by shoeper** [comment]
If that's the goal, why asking it in the seafile-server repository? By the way, you don't need to ask it at another place it won't happen. It'd take multiple years of manpower.
