### ISSUE TITLE
Access denied for user root@localhost

### ISSUE THREAD

**Issue by limbit** [SeafileDE/seafile-server-installer#7]
when running the script the following error occurs:

ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
The user name should be more than 2 bytes and less than 16 bytes, only digits,  alphabetes and '-', '_' are allowedsed: kann /opt/seafile/ccnet/ccnet.conf

after the installation the Nginx causes a 502 bad gateway. 

i executed the script for ubuntu.

**Comment by alexanderjackson** [comment]
Can you try setting "SERVER_NAME=$(hostname -s | cut -c -16)" in the Vars? Like here: https://github.com/SeafileDE/seafile-server-installer/blob/master/seafile-ce_debian-jessie-amd64

**Comment by alexanderjackson** [comment]
Can you access the MySQL command line as root simply by running `mysql` on the shell?

**Comment by limbit** [comment]
Yes, the SERVER_NAME can be set and is correctly.

Mysql can not be accessed with the root user:
/tmp# mysql
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

**Comment by alexanderjackson** [comment]
So the database credentials are wrong. Did you run the installer more then once?

**Comment by limbit** [comment]
no, i even did a restore on the VM to the fresh installed system and tried it again: same problem. 

The system is Ubuntu 14.04.2 server

**Comment by alexanderjackson** [comment]
I just tested the installer on Ubuntu 14.04 (64bit) and it works for me.

Make sure you you switch to root with `sudo su` before running

<pre>
cd /tmp
wget --no-check-certificate https://raw.githubusercontent.com/SeafileDE/seafile-server-installer/master/seafile-ce_ubuntu-trusty-amd64
time bash seafile-ce_ubuntu-trusty-amd64
</pre>

Running the installer with sudo will not work. Make sure you are running the newest installer. A older version might contain bugs...

If it still wont work, you need to enable the debug mode and look out for errors during the installation. I will try to implement a full logging option in the meantime.

**Comment by alexanderjackson** [comment]
Run this debugging version of the installer instead:

<pre>
cd /tmp
wget --no-check-certificate https://raw.githubusercontent.com/SeafileDE/seafile-server-installer/master/seafile-ce_ubuntu-trusty-amd64-debug
time bash seafile-ce_ubuntu-trusty-amd64-debug
</pre>

Then send the logfile /root/debug_aio_seafile-server.log to alexander.jackson@seafile.de

**Comment by limbit** [comment]
the debug script worked finally. Additionally root was accessed through 'sudo su' instead of 'sudo bash'. Perhaps this caused the error. 

Thanks for the hints and for your very good script! This saves a lot of time ;)

**Comment by alexanderjackson** [comment]
Sorry about that! I thought it was clear that the switch has to be done with `sudo su` before running the installer. I never really thought about it since this is my default way to change to root. I'll add the info to the installation description...
