### ISSUE TITLE
Install script (seafile-ce_ubuntu-trusty-amd64) fails to configure seafile

### ISSUE THREAD

**Issue by msplival** [SeafileDE/seafile-server-installer#81]
After cloning the latest install script from github and running it, installer fails to configure seafile:

Done.
Starting productive Seafile server
failed to run "ccnet-server -t"

Running it manually produces the same error:

root@seafile:~# /etc/init.d/seafile-server start
failed to run "ccnet-server -t"

The seafile.init.log reveals this:

[04/27/16 09:44:44] ../common/session.c(132): using config file /opt/seafile/conf/ccnet.conf
[04/27/16 09:44:44] ../common/session.c(138): Can't load config file /opt/seafile/conf/ccnet.conf.

**Comment by pagnotta** [comment]
I think the default location for configuration files has been changed to `/opt/seafile/conf/`, but this is not yet adjusted in the install script.

When moving `ccnet.conf` and `seafile.conf` manually to the `/opt/seafile/conf/` folder, seafile can be successfully started.

I guess the default file paths need to be adjusted, shouldn't be to hard.

**Comment by shoeper** [comment]
@pagnotta could you submit a PR?

**Comment by pagnotta** [comment]
I am not sure I will send a PR. Should I have the time and be able to fix it, I will send a PR though. But I hoped that one of the authors might be able to fix it!?

I discovered that also `seahub_settings.py` needs to be moved as well. So for a temporary fix the files

```
/opt/seafile/ccnet/ccnet.conf
/opt/seafile/seafile-data/seafile.conf
/opt/seafile/seahub_settings.py
```

need to be moved to the `/opt/seafile/conf/` folder. Then it works for me. Also mentioned here in post #118:

https://forum.seafile.de/t/seafile-server-installer-for-production-ready-seafile-ce-and-pro-installations/1464?page=5

EDIT: https connection timing out, only http possible. Also `seafile-server-change-address` woukd need to be adjusted, it writes the new configuration files in the wrong places.

**Comment by pagnotta** [comment]
As you can see I submitted a PR now.

**Comment by alexanderjackson** [comment]
This installer is deprecated and no longer supported. I'm closing the issue.
