### ISSUE TITLE
Doesn't check for existing installation

### ISSUE THREAD

**Issue by zhuanyi** [SeafileDE/seafile-server-installer#82]
This script does not check for existing installation of software packages, for example Apache2 is installed on both Debian 7 and 8 by default and if Apache is installed, Nginx won't start automatically.

Also I think there should be an option to use sqlLite as well, it would be great for servers with limited RAM.

**Comment by shoeper** [comment]
This is currently just to install Seafile on a fresh system.

**Comment by zhuanyi** [comment]
Hi,

Apache is installed on a **FRESHLY INSTALLED** Debian.

**Comment by shoeper** [comment]
Normally not.

I'm using both Debian Wheezy and Debian Jessie and Apache has never been preinstalled.
