### ISSUE TITLE
Problems on Jessie if systemd-sysv is not installed

### ISSUE THREAD

**Issue by seidler2547** [SeafileDE/seafile-server-installer#85]
The script should add the package "systemd-sysv" on Jessie-based systems. I used the script in a LXC set up from a Jessie template which didn't have this package, and even though things installed fine, the systemd-only services (seafile.service and seahub.service) didn't start and weren't enabled. After installing the systemd-sysv package and manually enabling and starting these two services, things worked fine.

**Comment by alexanderjackson** [comment]
Installing `systemd-sysv` doesn't work for me on LXE-based (Proxmox VE) Jessie server. Trying to execute `systemctl` fails with `Failed to get D-Bus connection: Unknown error -1`.

**Comment by seidler2547** [comment]
IIRC `systemctl` only works after restarting the container if it wasn't installed initially.

**Comment by alexanderjackson** [comment]
That was easy ;-). Now I just need to think about how to implement this without causing general usability issues.

**Comment by seidler2547** [comment]
I think `systemctl enable` doesn't do any magic. It symlinks `/etc/systemd/system/seafile.service` to `/etc/systemd/system/multi-user.target.wants/seafile.service`, so a `ln -s` should do the same. First-time start could still be using `/etc/init.d/seafile`. (And the same for seahub`.

**Comment by alexanderjackson** [comment]
Apparently there's a environment variable called `container`. If it's present and set to lxc we could setup sysvinit instead of systemd start scripts on such machines. Alternatively we might also be able to search for lxc references in `/proc/1/environ`. I think this would be a clean solution for this issue.

**Comment by seidler2547** [comment]
Yes, I also found that `grep -qa container=lxc /proc/1/environ` is a good way of detecting it.

**Comment by alexanderjackson** [comment]
Fixed in https://github.com/syncwerk/syncwerk-server-installer/commit/770269fa08588e60cf7e1cbe57ec4667ef0f0712
