### ISSUE TITLE
nginx is configured for IPv4 only

### ISSUE THREAD

**Issue by seidler2547** [SeafileDE/seafile-server-installer#86]
The default nginx binding is IPv4 only. Can the `listen` statements be changed to

```
listen [::]:80 ipv6only=off;
```

and 

```
listen [::]:443 ipv6only=off;
```

That would be great! nginx then listens on IPv4 _and_ IPv6.

**Comment by alexanderjackson** [comment]
Done for seafile_v5_debian https://github.com/seafile/seafile-server-installer/commit/af0ab849b5db24818b5b7d5b3272a9d54b3bbbba and seafile_v5_centos https://github.com/seafile/seafile-server-installer/commit/53e1ffc1c57ca7c77b98eba53a51f0dd413735c1
