### ISSUE TITLE
Ubuntu trusty 64bit fails to install MariaDB

### ISSUE THREAD

**Issue by Munken** [SeafileDE/seafile-server-installer#87]
MariaDB fails to install due to missing dependency
```
 * Stopping MariaDB database server mysqld                                                      [ OK ] 
chown: cannot access '/var/run/mysqld': No such file or directory
/var/lib/dpkg/info/mariadb-server-5.5.postinst: line 149: logger: command not found
/var/lib/dpkg/info/mariadb-server-5.5.postinst: line 224: logger: command not found
```
This can be fixed by installing `bsdutils`

Source:   
http://askubuntu.com/questions/506243/mysql-strange-installations-problems-logger-command-not-found

**Comment by alexanderjackson** [comment]
Thank you! This is fixed now > https://github.com/seafile/seafile-server-installer/commit/232ee53b983f0aadc6aab433b029ffe45a280cb6#diff-220c190d219f18ad25e38f6fc319cf5f
