### ISSUE TITLE
syncwerk_v5_centos breaks in line 679

### ISSUE THREAD

**Issue by schwindp** [SeafileDE/seafile-server-installer#89]
syncwerk_v5_centos breaks in line 679 since the downloaded package installs into `/opt/syncwerk/seafile-server-5.1.3` instead of `/opt/syncwerk/syncwerk-server-*`

Thanks.

`syncwerk_v5_centos: line 679: /opt/syncwerk/syncwerk-server-*//seahub/sql/mysql.sql: No such file or directory`

**Comment by lordwardave** [comment]
same issue

**Comment by alexanderjackson** [comment]
Since we are restructuring the installation procedure the syncwerk_v5_centos installer is deprecated and no longer supported. A new installation method for Syncwerk on Centos will follow later this year. I'm closing the issue.
