### ISSUE TITLE
seafile_ubuntu failed

### ISSUE THREAD

**Issue by AntoinePierre** [SeafileDE/seafile-server-installer#90]
Hello,

I'm trying to install the script seafile_ubuntu with no luck.
The script is always failing while dpkg is working ...

And the log file is not created so I really dont have any way to diagnose the problem ...
Any help will be very appreciated.

Regards.

Error is bellow :
-------------------------------------

Setting up libtimedate-perl (2.3000-2) ...
Setting up libhttp-date-perl (6.02-1) ...
Setting up libio-html-perl (1.001-1) ...
Setting up liblwp-mediatypes-perl (6.02-1) ...
Setting up libhttp-message-perl (6.11-1) ...
Setting up mariadb-server (10.0.29-0ubuntu0.16.04.1) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Processing triggers for systemd (229-4ubuntu17) ...
Processing triggers for ureadahead (0.100.0-19) ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100    10  100    10    0     0      6      0  0:00:01  0:00:01 --:--:--    28

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by shoeper** [comment]
According to the repo currently only Debian is supported.

https://github.com/syncwerk/syncwerk-server-installer/blob/master/syncwerk_v5_debian

**Comment by AntoinePierre** [comment]
Hello,

I'm so sorry, I mised the most important .... Must be dumb sometimes ...
Thanks for the replay.

Regards
