### ISSUE TITLE
disable selinux check for lxc installation?

### ISSUE THREAD

**Issue by n1ete** [SeafileDE/seafile-server-installer#92]
Actually the script isnt working in lxc based enviroment because of the missing selinux .conf file.
I use a Proxmox vhost and it uses apparmor instead...
is it possible (does ist make sense) to make the script work for an proxmox lxc enviroment?

thanks

**Comment by alexanderjackson** [comment]
I use the installer on Proxmox based LXC machines without issues. Which error messages are you receiving? Which LXC image are you using?

**Comment by n1ete** [comment]
thanks for asking,
nevermind, i tried it first with an centos turnkey os. a soon as i switched to debian it worked fine!
