### ISSUE TITLE
Server hangs up at Line 788

### ISSUE THREAD

**Issue by Ne00n** [SeafileDE/seafile-server-installer#93]
Hey,

I tried your script on debian 8 64bit and it seems like there is missing a file:

syncwerk_v5_debian: line 788: /opt/syncwerk/syncwerk-server-*/seahub/sql/mysql.sql: No such file or directory

Any idea how to fix it?

**Comment by Ne00n** [comment]
Also there is a typo:
apt-get git lsb-release ca-certificates net-tools -y

Its apt-get install

**Comment by alexanderjackson** [comment]
Thank you. The problems where solved a while ago.

**Comment by Ne00n** [comment]
haha no, they still fail.
